"""update restaurants table

Revision ID: 9521aa45bfef
Revises: 4bfc183db66e
Create Date: 2026-04-19 05:03:00.420093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9521aa45bfef'
down_revision: Union[str, Sequence[str], None] = '4bfc183db66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('cuisine', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'location')
    op.drop_column('restaurants', 'cuisine')
    # ### end Alembic commands ###
